server:
  port: 1213
  servlet:
    context-path: /ProductRestApi

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/searchdb
    username: root
    password: root

  jpa:
    show-sql: true 
    jpa:
    hibernate:
      ddl-auto: update 









